# Generated by Django 5.2.8 on 2025-11-30 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_savedquestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('timer_seconds', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='users.questionnaire')),
            ],
            options={
                'db_table': 'users_cuestionario',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='cuestionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.cuestionario'),
        ),
        migrations.DeleteModel(
            name='SavedQuestionnaire',
        ),
    ]
