# Generated by Django 5.2.8 on 2025-12-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_question_cuestionario_savedquestionnaire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedQuestionnaire',
        ),
    ]
