# Generated by Django 5.2.8 on 2025-12-02 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_savedquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='users.questionnaire')),
            ],
            options={
                'db_table': 'cuestionarios',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='cuestionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cuestionario'),
        ),
    ]
