# Generated by Django 5.2.8 on 2025-12-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_question_time_cuestionario_question_cuestionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
