# Generated by Django 5.2.8 on 2026-01-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_question_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='access_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
