# Generated by Django 5.2.8 on 2026-01-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_questionnaire_access_code_questionnaire_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='current_question_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
