# Generated by Django 5.2.8 on 2026-01-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_questionnaire_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='active_cuestionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_questionnaires', to='users.cuestionario'),
        ),
    ]
